version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:16.15.0 
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Disable jekyll builds
          command: touch ./public/.nojekyll
      - add_ssh_keys:
          fingerprints:
            - "30:91:7d:df:dd:00:cc:fa:0b:cf:eb:53:e8:7f:18:af"
      - run:
          command: echo 'stid.me' > ./public/CNAME && yarn gh-pages --message "[skip ci] Updates" -d public
          name: Deploy github Pages



workflows:
  test:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: master # only deploy when on main
